### ISSUE TITLE
How to bring controller to foreground from Alloy.Controllers

### ISSUE THREAD

**Issue by hannta** [jasonkneen/AlloyXL#1]
Thanks for the great lib, this is more like an question than issue.

As the controllers are saved to Alloy.Controllers, how can I open/bring previously opened controller (window) to foreground.

Lets say user navigates: index -> controller1 -> controller2.

In controller2, can I just call `Alloy.Controllers.index.getView().open()` to go back to index controller/window?

**Comment by jasonkneen** [comment]
That should bring it back to foreground yes.

**Comment by hannta** [comment]
I tried this but nothing happens :) 
Im using android to try this.

**Comment by jasonkneen** [comment]
ok -- not sure -- not an issue with AlloyXL though -- as you're simply getting a normal Ti View so whatever you would normally do with that is what you need to do.

Bigger question is -- why are you having to do this? Sounds like if you have Index > Controller 1 > Controller 2 then to get back to index you close Controller 1 & 2?

**Comment by hannta** [comment]
Yes, this is not issue on the AlloyXL, im just wondering why im not able to open the index again from Alloy.Controllers. If I create new index controller, it works fine `Alloy.createController('index', {}).getView().open()`

What is typical solution for this kind of "go back multiple controllers" scenario? Chain callback with these controllers?

**Comment by jasonkneen** [comment]
Typically you navigate back through your stack so:

Controller 1 > Controller 2 > Controller 3

If you want to go back from Controller 3 to Controller 2, you close Controller 3

If you want to go back from Controller 3 to Controller 1 you close Controller 2 FIRST and then controller 3, which will jump straight back to Controller 1

Don't create new instances as you're creating new / duplicate controllers and that'll cause lots of issues.

**Comment by jasonkneen** [comment]
If you need further help, try the community [Slack](http://TiSlack.org)
