### ISSUE TITLE
Error ENV_DEV... I have some issues to find how to use your module!

### ISSUE THREAD

**Issue by jimmygarcia-dev** [jasonkneen/AlloyXL#12]
[ERROR] :  TiExceptionHandler:                     if (ENV_DEV) console.log("::AlloyXL:: controller " + name + " layout finished");
[ERROR] :  TiExceptionHandler:                     ^
[ERROR] :  TiExceptionHandler: ReferenceError: ENV_DEV is not defined

**Comment by jasonkneen** [comment]
how are you adding it to your project, are you requiring it from another module? Any chance of a sample app that demonstrates this?

**Comment by jimmygarcia-dev** [comment]
Thanks for answer, I´m trying to copy dist in "commonjs" > "alloyxl", after that i´m trying to invoque "require("alloyxl");" in my index.js after the documentation tells me that the normal invoque of "Alloy.createController("autenticacion").getView().open();" but doesn´t seems to work.

**Comment by jasonkneen** [comment]
Ahh ok -- move the reste.js file from the commonjs folder to the /app/lib folder and try again -- that's probably it

**Comment by ShahrayarSoueid** [comment]
hey @jasonkneen , 
I'm facing the same problem, I don't have reste.js file in commonjs

Can you help?
Thanks

**Comment by jasonkneen** [comment]
Just place in app/lib and all good.
