### ISSUE TITLE
LiveView broken

### ISSUE THREAD

**Issue by apocalypsebg** [jasonkneen/AlloyXL#7]
LiveView seems to stop working when using the library.... The controllers are not reloaded?

**Comment by jasonkneen** [comment]
Sorry, what does "broken" and "stop working" mean? What errors do you get? Can you provide more information?

**Comment by apocalypsebg** [comment]
Well either I'm doing something wrong (quite possible), but when using the library, the controllers are not being reloaded when they are changed - for example backgroundColor remains the same and etc...

**Comment by jasonkneen** [comment]
Need to see a sample app demoing this as not seeing this

**Comment by jasonkneen** [comment]
There's definitely something else going on here -- can you share a sample app that doesn't work so I can test?

**Comment by Topener** [comment]
fyi: I'm seeing issues with Staballoy too...

**Comment by jasonkneen** [comment]
just not seeing it -- able to make changes and reloads and works fine so interested to find out more / see examples

**Comment by jasonkneen** [comment]
Closing as can't reproduce.
